### ISSUE TITLE
How to overwrite the default host dict

### ISSUE THREAD

**Issue by rall0r** [bechtoldt/saltstack-network-formula#13]
Hi,
I need to disable the IPv6 entries in `/etc/hosts` like they are defined at the `defaults.yaml`.
So we need a dict like this:
```yaml
  hosts:
    def_entries:
      - name: localhost
        ip: 127.0.0.1
      - name: localhost.localdomain
        ip: 127.0.0.1
```
I am unable to overwrite the default values with a pillar because it looks like the key of a pillar `hosts:def_entries` is added  to `hosts:def_entries` of the `defaults.yaml`.

I made a pillar like this:
```yaml
network:
  lookup:
    hosts:
      def_entries:
        - name: localhost
          ip: 127.0.0.1
        - name: localhost.localdomain
          ip: 127.0.0.1
```

This leads to a datastructure `hosts` inside your `hosts.sls` like this:

```
yaml = [{ip: 127.0.0.1, name: localhost}, {ip: 127.0.0.1, name: localhost.localdomain}, {
    ip: '::1', name: localhost}, {ip: '::1', name: ip6-localhost}, {ip: '::1', name: ip6-loopback},
  {ip: 'fe00::0', name: ip6-localnet}, {ip: 'ff00::0', name: ip6-mcastprefix}, {ip: 'ff02::1',
    name: ip6-allnodes}, {ip: 'ff02::2', name: ip6-allrouters}, {ip: 'ff02::3', name: ip6-allhosts},
  {ip: 127.0.0.1, name: localhost}, {ip: 127.0.0.1, name: localhost.localdomain}]
```
As you can see, there are 2 `{ip: 127.0.0.1, name: localhost}` entries.

Any idea how to fix this?
Kind regards
ralf
