### ISSUE TITLE
Unable to add many IPs to single interface

### ISSUE THREAD

**Issue by morsik** [bechtoldt/saltstack-network-formula#8]
This causes `Conflicting ID 'network_lo'` when I want to assign many addresses to loopback interface (or any other).

Example:

```yaml
network:
  interfaces:
    - name: lo
      ipaddr: 127.1.1.1
      netmask: 255.255.255.255
    - name: lo
      ipaddr: 127.1.1.2
      netmask: 255.255.255.255
```
